name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "sbt"

      - uses: sbt/setup-sbt@v1


      - name: SBT remote cache
        id: remote-cache
        uses: actions/cache@v3
        with:
          path: ./.remote-cache
          key: ${{ runner.os }}-remote-cache

      - name: Pull cache
        run: sbt --client pullRemoteCache || echo 'remote cache not found'

      - name: Test
        run: sbt --client ci

      - name: Test publishing
        run: sbt --client publishLocal

      - name: Push cache
        run: sbt --client pushRemoteCache || echo 'oh well then'

      - name: Publish ${{ github.ref }}
        run: sbt ci-release
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  mergify-build-checkpoint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: I only exist to please Mergify :(
        run: echo "It's a sad existence but necessary"
